### ISSUE TITLE
Wiki page (tree) not shown in Nextcloud XWiki App

### ISSUE THREAD

**Issue by sebastiaanveld** [nextcloud/xwiki#10]
For now I only can find content in the wiki using the Nextcloud search button, there are no mail pages or a page tree shown on the left of the Nextcloud XWiki App. Played a bit with rights as suggested in #2, but nothing shows on the left to click on for the user.

![image](https://user-images.githubusercontent.com/37268999/230357208-dd959a0b-4224-43ae-9032-50ebe5dfcf7e.png)

As a user I would expect wiki parent pages to show up when the user has access to them and walk the wiki pages like using the XWiki GUI.

Environment:
XWiki 15.2
XWiki Nextcloud Extension 1.3
Nextcloud 25.0.5, PHP8.1
Nextcloud XWiki App 0.0.5

**Comment by raphj** [comment]
Have you enabled the integrated mode in your user settings?

**Comment by sebastiaanveld** [comment]
Yes, integrated mode is enabled.

**Comment by Thiwico** [comment]
Hello, I have the same problem.

Current xwiki version
XWiki Nextcloud Extension 1.3
Nextcloud 25.0.5, PHP8.1
Nextcloud XWiki App 0.0.5

And the content of the Xwiki is not displayed in the Nextcloud for me either.

See the screenshot:

<img width="923" alt="Screenshot 2023-04-19 001533" src="https://user-images.githubusercontent.com/82508582/232917149-24fdd296-6743-4976-b5d2-0e1ecf1f8001.png">

<img width="197" alt="Screenshot 2023-04-19 Mode" src="https://user-images.githubusercontent.com/82508582/232917292-dc34a267-19f1-4adf-8dd8-25f377ff79a2.png">

**Comment by raphj** [comment]
@fenvarien @sebastiaanveld @Thiwico this was due to a condition that was hiding the navigation tree when there was not more than one registered instance.

This was because we wanted to simplify the UI in case there was only one instance registered but we are obviously not ready for this / things have changed in a way that broke the intent since then.

I didn't notice because I'm testing with several instances.

This is now fixed in the 0.0.6 version of the app I just released. Closing but feel free to reopen if you still see this issue.

Sorry for the delay, and thanks for the feedback!
